// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Student struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Standard             string   `protobuf:"bytes,4,opt,name=Standard,proto3" json:"Standard,omitempty"`
	SchoolCode           int64    `protobuf:"varint,5,opt,name=SchoolCode,proto3" json:"SchoolCode,omitempty"`
	IdentityNumber       int64    `protobuf:"varint,6,opt,name=IdentityNumber,proto3" json:"IdentityNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Student) GetStandard() string {
	if m != nil {
		return m.Standard
	}
	return ""
}

func (m *Student) GetSchoolCode() int64 {
	if m != nil {
		return m.SchoolCode
	}
	return 0
}

func (m *Student) GetIdentityNumber() int64 {
	if m != nil {
		return m.IdentityNumber
	}
	return 0
}

type AddStudentRequest struct {
	Input                *Student `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddStudentRequest) Reset()         { *m = AddStudentRequest{} }
func (m *AddStudentRequest) String() string { return proto.CompactTextString(m) }
func (*AddStudentRequest) ProtoMessage()    {}
func (*AddStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{1}
}

func (m *AddStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStudentRequest.Unmarshal(m, b)
}
func (m *AddStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStudentRequest.Marshal(b, m, deterministic)
}
func (m *AddStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStudentRequest.Merge(m, src)
}
func (m *AddStudentRequest) XXX_Size() int {
	return xxx_messageInfo_AddStudentRequest.Size(m)
}
func (m *AddStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddStudentRequest proto.InternalMessageInfo

func (m *AddStudentRequest) GetInput() *Student {
	if m != nil {
		return m.Input
	}
	return nil
}

type GetStudentRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudentRequest) Reset()         { *m = GetStudentRequest{} }
func (m *GetStudentRequest) String() string { return proto.CompactTextString(m) }
func (*GetStudentRequest) ProtoMessage()    {}
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{2}
}

func (m *GetStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentRequest.Unmarshal(m, b)
}
func (m *GetStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentRequest.Marshal(b, m, deterministic)
}
func (m *GetStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentRequest.Merge(m, src)
}
func (m *GetStudentRequest) XXX_Size() int {
	return xxx_messageInfo_GetStudentRequest.Size(m)
}
func (m *GetStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentRequest proto.InternalMessageInfo

func (m *GetStudentRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteStudentRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStudentRequest) Reset()         { *m = DeleteStudentRequest{} }
func (m *DeleteStudentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStudentRequest) ProtoMessage()    {}
func (*DeleteStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{3}
}

func (m *DeleteStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStudentRequest.Unmarshal(m, b)
}
func (m *DeleteStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStudentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStudentRequest.Merge(m, src)
}
func (m *DeleteStudentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStudentRequest.Size(m)
}
func (m *DeleteStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStudentRequest proto.InternalMessageInfo

func (m *DeleteStudentRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type UpdateStudentRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Input                *Student `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStudentRequest) Reset()         { *m = UpdateStudentRequest{} }
func (m *UpdateStudentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStudentRequest) ProtoMessage()    {}
func (*UpdateStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{4}
}

func (m *UpdateStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStudentRequest.Unmarshal(m, b)
}
func (m *UpdateStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStudentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStudentRequest.Merge(m, src)
}
func (m *UpdateStudentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStudentRequest.Size(m)
}
func (m *UpdateStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStudentRequest proto.InternalMessageInfo

func (m *UpdateStudentRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateStudentRequest) GetInput() *Student {
	if m != nil {
		return m.Input
	}
	return nil
}

type AddStudentResponse struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddStudentResponse) Reset()         { *m = AddStudentResponse{} }
func (m *AddStudentResponse) String() string { return proto.CompactTextString(m) }
func (*AddStudentResponse) ProtoMessage()    {}
func (*AddStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{5}
}

func (m *AddStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStudentResponse.Unmarshal(m, b)
}
func (m *AddStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStudentResponse.Marshal(b, m, deterministic)
}
func (m *AddStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStudentResponse.Merge(m, src)
}
func (m *AddStudentResponse) XXX_Size() int {
	return xxx_messageInfo_AddStudentResponse.Size(m)
}
func (m *AddStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddStudentResponse proto.InternalMessageInfo

func (m *AddStudentResponse) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type GetStudentsRequest struct {
	SchoolCode           int64    `protobuf:"varint,1,opt,name=SchoolCode,proto3" json:"SchoolCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudentsRequest) Reset()         { *m = GetStudentsRequest{} }
func (m *GetStudentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStudentsRequest) ProtoMessage()    {}
func (*GetStudentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{6}
}

func (m *GetStudentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentsRequest.Unmarshal(m, b)
}
func (m *GetStudentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentsRequest.Marshal(b, m, deterministic)
}
func (m *GetStudentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentsRequest.Merge(m, src)
}
func (m *GetStudentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStudentsRequest.Size(m)
}
func (m *GetStudentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentsRequest proto.InternalMessageInfo

func (m *GetStudentsRequest) GetSchoolCode() int64 {
	if m != nil {
		return m.SchoolCode
	}
	return 0
}

type GetStudentsResponse struct {
	Student              []*Student `protobuf:"bytes,1,rep,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetStudentsResponse) Reset()         { *m = GetStudentsResponse{} }
func (m *GetStudentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetStudentsResponse) ProtoMessage()    {}
func (*GetStudentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{7}
}

func (m *GetStudentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentsResponse.Unmarshal(m, b)
}
func (m *GetStudentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentsResponse.Marshal(b, m, deterministic)
}
func (m *GetStudentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentsResponse.Merge(m, src)
}
func (m *GetStudentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetStudentsResponse.Size(m)
}
func (m *GetStudentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentsResponse proto.InternalMessageInfo

func (m *GetStudentsResponse) GetStudent() []*Student {
	if m != nil {
		return m.Student
	}
	return nil
}

func init() {
	proto.RegisterType((*Student)(nil), "pb.Student")
	proto.RegisterType((*AddStudentRequest)(nil), "pb.AddStudentRequest")
	proto.RegisterType((*GetStudentRequest)(nil), "pb.GetStudentRequest")
	proto.RegisterType((*DeleteStudentRequest)(nil), "pb.DeleteStudentRequest")
	proto.RegisterType((*UpdateStudentRequest)(nil), "pb.UpdateStudentRequest")
	proto.RegisterType((*AddStudentResponse)(nil), "pb.AddStudentResponse")
	proto.RegisterType((*GetStudentsRequest)(nil), "pb.GetStudentsRequest")
	proto.RegisterType((*GetStudentsResponse)(nil), "pb.GetStudentsResponse")
}

func init() {
	proto.RegisterFile("student.proto", fileDescriptor_94a1c1b032ad0c00)
}

var fileDescriptor_94a1c1b032ad0c00 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0x7d, 0x6d, 0xf9, 0x78, 0xef, 0x12, 0xc8, 0xe3, 0x3e, 0x1e, 0x4e, 0x58, 0x18, 0x1c, 0x23,
	0x61, 0xc5, 0x02, 0x8d, 0x1b, 0x35, 0x91, 0x40, 0x62, 0xba, 0x61, 0x41, 0xe3, 0x0f, 0x68, 0x99,
	0x1b, 0x25, 0x81, 0xb6, 0xb6, 0x53, 0x13, 0x7f, 0x8f, 0xff, 0xca, 0x5f, 0x63, 0x3a, 0xa5, 0x96,
	0x96, 0x02, 0xbb, 0xe1, 0xcc, 0x39, 0xf7, 0x9e, 0x33, 0x87, 0x42, 0x33, 0x94, 0x91, 0x20, 0x57,
	0x8e, 0xfc, 0xc0, 0x93, 0x1e, 0xea, 0xbe, 0xc3, 0x3f, 0x35, 0xa8, 0x5b, 0x09, 0x8a, 0x2d, 0xd0,
	0xcd, 0x19, 0xd3, 0xfa, 0xda, 0xd0, 0x58, 0xe8, 0xe6, 0x0c, 0x11, 0x2a, 0x73, 0x7b, 0x43, 0x4c,
	0xef, 0x6b, 0xc3, 0x3f, 0x0b, 0x75, 0xc6, 0xbf, 0x60, 0x4c, 0x5e, 0x88, 0x19, 0x8a, 0x14, 0x1f,
	0xb1, 0x07, 0xbf, 0x2d, 0x69, 0xbb, 0xc2, 0x0e, 0x04, 0xab, 0x28, 0xe6, 0xcf, 0x6f, 0x3c, 0x07,
	0xb0, 0x96, 0xaf, 0x9e, 0xb7, 0x9e, 0x7a, 0x82, 0x58, 0x55, 0x89, 0x76, 0x10, 0x1c, 0x40, 0xcb,
	0x8c, 0x57, 0xaf, 0xe4, 0xc7, 0x3c, 0xda, 0x38, 0x14, 0xb0, 0x9a, 0xe2, 0x14, 0x50, 0x7e, 0x0b,
	0xed, 0x89, 0x10, 0x5b, 0x9f, 0x0b, 0x7a, 0x8b, 0x28, 0x94, 0x78, 0x01, 0xd5, 0x95, 0xeb, 0x47,
	0x52, 0x39, 0x6e, 0x8c, 0x1b, 0x23, 0xdf, 0x19, 0xa5, 0x94, 0xe4, 0x86, 0x5f, 0x42, 0xfb, 0x89,
	0x64, 0x41, 0x57, 0x88, 0xc9, 0x07, 0xd0, 0x99, 0xd1, 0x9a, 0x24, 0x9d, 0xe0, 0x99, 0xd0, 0x79,
	0xf6, 0x85, 0x7d, 0x8a, 0x97, 0xf9, 0xd2, 0x0f, 0xfa, 0xba, 0x03, 0xdc, 0xcd, 0x13, 0xfa, 0x9e,
	0x1b, 0x12, 0x5e, 0x41, 0x7d, 0x5b, 0x50, 0x59, 0xa4, 0xf4, 0x8e, 0xdf, 0x00, 0x66, 0xa1, 0xc2,
	0xd4, 0x45, 0xfe, 0xa9, 0xb5, 0xe2, 0x53, 0xf3, 0x7b, 0xf8, 0x97, 0x53, 0x95, 0xed, 0x34, 0x0e,
	0xed, 0x1c, 0x7f, 0xe9, 0xd0, 0xda, 0x82, 0x16, 0x05, 0xef, 0xab, 0x25, 0xe1, 0x03, 0x40, 0x96,
	0x01, 0xff, 0xc7, 0xb2, 0xbd, 0x8e, 0x7a, 0xdd, 0x22, 0x9c, 0xac, 0xe5, 0xbf, 0x62, 0x79, 0xe6,
	0x27, 0x91, 0xef, 0x55, 0x75, 0x44, 0x3e, 0x85, 0x66, 0xae, 0x0c, 0x64, 0x31, 0xb5, 0xac, 0x9f,
	0xe3, 0x43, 0x72, 0xcd, 0x27, 0x43, 0xca, 0xfe, 0x0c, 0x47, 0x86, 0x3c, 0x42, 0x63, 0xe7, 0x61,
	0xb1, 0x9b, 0x4f, 0x92, 0xf6, 0xd3, 0x3b, 0xdb, 0xc3, 0xd3, 0x09, 0x4e, 0x4d, 0x7d, 0x8e, 0xd7,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x86, 0xbf, 0x4f, 0x1f, 0x9f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StudentServiceClient is the client API for StudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentServiceClient interface {
	AddStudent(ctx context.Context, in *AddStudentRequest, opts ...grpc.CallOption) (*AddStudentResponse, error)
	GetStudent(ctx context.Context, in *GetStudentRequest, opts ...grpc.CallOption) (*AddStudentResponse, error)
	UpdateStudent(ctx context.Context, in *UpdateStudentRequest, opts ...grpc.CallOption) (*AddStudentResponse, error)
	DeleteStudent(ctx context.Context, in *DeleteStudentRequest, opts ...grpc.CallOption) (*AddStudentResponse, error)
	GetStudents(ctx context.Context, in *GetStudentsRequest, opts ...grpc.CallOption) (*GetStudentsResponse, error)
}

type studentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentServiceClient(cc grpc.ClientConnInterface) StudentServiceClient {
	return &studentServiceClient{cc}
}

func (c *studentServiceClient) AddStudent(ctx context.Context, in *AddStudentRequest, opts ...grpc.CallOption) (*AddStudentResponse, error) {
	out := new(AddStudentResponse)
	err := c.cc.Invoke(ctx, "/pb.StudentService/AddStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) GetStudent(ctx context.Context, in *GetStudentRequest, opts ...grpc.CallOption) (*AddStudentResponse, error) {
	out := new(AddStudentResponse)
	err := c.cc.Invoke(ctx, "/pb.StudentService/GetStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) UpdateStudent(ctx context.Context, in *UpdateStudentRequest, opts ...grpc.CallOption) (*AddStudentResponse, error) {
	out := new(AddStudentResponse)
	err := c.cc.Invoke(ctx, "/pb.StudentService/UpdateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) DeleteStudent(ctx context.Context, in *DeleteStudentRequest, opts ...grpc.CallOption) (*AddStudentResponse, error) {
	out := new(AddStudentResponse)
	err := c.cc.Invoke(ctx, "/pb.StudentService/DeleteStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) GetStudents(ctx context.Context, in *GetStudentsRequest, opts ...grpc.CallOption) (*GetStudentsResponse, error) {
	out := new(GetStudentsResponse)
	err := c.cc.Invoke(ctx, "/pb.StudentService/GetStudents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServiceServer is the server API for StudentService service.
type StudentServiceServer interface {
	AddStudent(context.Context, *AddStudentRequest) (*AddStudentResponse, error)
	GetStudent(context.Context, *GetStudentRequest) (*AddStudentResponse, error)
	UpdateStudent(context.Context, *UpdateStudentRequest) (*AddStudentResponse, error)
	DeleteStudent(context.Context, *DeleteStudentRequest) (*AddStudentResponse, error)
	GetStudents(context.Context, *GetStudentsRequest) (*GetStudentsResponse, error)
}

// UnimplementedStudentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStudentServiceServer struct {
}

func (*UnimplementedStudentServiceServer) AddStudent(ctx context.Context, req *AddStudentRequest) (*AddStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStudent not implemented")
}
func (*UnimplementedStudentServiceServer) GetStudent(ctx context.Context, req *GetStudentRequest) (*AddStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudent not implemented")
}
func (*UnimplementedStudentServiceServer) UpdateStudent(ctx context.Context, req *UpdateStudentRequest) (*AddStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStudent not implemented")
}
func (*UnimplementedStudentServiceServer) DeleteStudent(ctx context.Context, req *DeleteStudentRequest) (*AddStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStudent not implemented")
}
func (*UnimplementedStudentServiceServer) GetStudents(ctx context.Context, req *GetStudentsRequest) (*GetStudentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudents not implemented")
}

func RegisterStudentServiceServer(s *grpc.Server, srv StudentServiceServer) {
	s.RegisterService(&_StudentService_serviceDesc, srv)
}

func _StudentService_AddStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).AddStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StudentService/AddStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).AddStudent(ctx, req.(*AddStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_GetStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).GetStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StudentService/GetStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).GetStudent(ctx, req.(*GetStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_UpdateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).UpdateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StudentService/UpdateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).UpdateStudent(ctx, req.(*UpdateStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_DeleteStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).DeleteStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StudentService/DeleteStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).DeleteStudent(ctx, req.(*DeleteStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_GetStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).GetStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StudentService/GetStudents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).GetStudents(ctx, req.(*GetStudentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StudentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StudentService",
	HandlerType: (*StudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddStudent",
			Handler:    _StudentService_AddStudent_Handler,
		},
		{
			MethodName: "GetStudent",
			Handler:    _StudentService_GetStudent_Handler,
		},
		{
			MethodName: "UpdateStudent",
			Handler:    _StudentService_UpdateStudent_Handler,
		},
		{
			MethodName: "DeleteStudent",
			Handler:    _StudentService_DeleteStudent_Handler,
		},
		{
			MethodName: "GetStudents",
			Handler:    _StudentService_GetStudents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "student.proto",
}
